### PR TITLE
Setup CircleCI and Jest

### PR DESCRIPTION
**Pull request by zhujohnny**

### CODE REVIEW

**Comment by yanb2016** [comment]
Do more!

**Review by yanb2016 — APPROVED** [review]
doit

**Comment by zhujohnny** [comment]
[(L) set up Jest](https://trello.com/c/zTIKvtVb/7-l-set-up-jest)

**Comment by zhujohnny** [comment]
[(L) set up CircleCI](https://trello.com/c/ZRcCvjOG/14-l-set-up-circleci)

**Pull request merged**
